"""
Django settings for testserver project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import sys, os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.append(str(BASE_DIR) + '/../')

from config import localconfig
from config import logconfig

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = localconfig.wwwConfig['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = localconfig.wwwConfig['IS_DEBUG']

ALLOWED_HOSTS = localconfig.wwwConfig['ALLOWED_HOSTS']

LOG_LOCATION = localconfig.wwwConfig['LOG_LOCATION']
LOGGING = logconfig.getLogConfig(LOG_LOCATION, DEBUG, os.sep)

EMAIL_USE_TLS = localconfig.emailConfig['EMAIL_USE_TLS']
EMAIL_HOST = localconfig.emailConfig['EMAIL_HOST']
EMAIL_HOST_USER = localconfig.emailConfig['EMAIL_HOST_USER']
EMAIL_HOST_PASSWORD = localconfig.emailConfig['EMAIL_HOST_PASSWORD']
EMAIL_PORT = localconfig.emailConfig['EMAIL_PORT']

# Application definition

INSTALLED_APPS = [
    'apps.testapp',
    'apps.testapi',
    'rest_framework',
    'rest_framework.authtoken',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'testserver.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'testserver.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': localconfig.getDbConfig(BASE_DIR)
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = localconfig.wwwConfig['STATIC_URL']
STATIC_ROOT = localconfig.wwwConfig['STATIC_ROOT']
MEDIA_URL = localconfig.wwwConfig['MEDIA_URL']
MEDIA_ROOT = localconfig.wwwConfig['MEDIA_ROOT']
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
FIXTURE_DIRS = (
    os.path.join(BASE_DIR, 'fixtures/test/'),
)

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
