# Generated by Django 3.2.4 on 2023-03-22 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.model.customfields.nonnegativedecimalfield
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userUuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('userName', models.CharField(max_length=100)),
                ('userEmail', models.CharField(max_length=200)),
                ('userProfile', models.ImageField(blank=True, null=True, upload_to='')),
                ('profileCreateTime', models.DateTimeField(auto_now_add=True)),
                ('joinDate', models.DateTimeField(blank=True, null=True)),
                ('agreementExpiryDate', models.DateTimeField(blank=True, null=True)),
                ('profileBalance', lib.model.customfields.nonnegativedecimalfield.NonNegativeDecimalField(decimal_places=2, default=0, max_digits=12)),
                ('isDeleted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('userName', 'userEmail')},
            },
        ),
    ]
