from datetime import timedelta

DECIMAL_PLACES = 2
FIELD_MAX_DIGITS = 12
NAME_MAX_LINGTH = 100
EMAIL_MAX_LENGTH = 200
PASSWORD_MIN_LENGTH = 8
USERNAME_MAX_LENGTH = 150
PASSWORD_MAX_LENGTH = 128
EXPIRY_TIME = timedelta(seconds=5)
ROLE_PROPERTY = "role"
EMAIL_PROPERTY = "email"
FIELD_PROPERTY = "field"
ERROR_PROPERTY = "error"
MESSAGE_PROPERTY = "message"
PASSWORD_PROPERTY = "password"
ERROR_TYPE_PROPERTY = "errorType"
ERROR_MESSAGE_PROPERTY = "errorMessage"
FORM_SET_ERRORS_PROPERTY = "formSetErrors"
RETYPE_PASSWORD_PROPERTY = "retypePassword"
